project_id = "YOUR_DEV_PROJECT"
region     = "us-central1"
location   = "US"
bucket_name = "ecco-studio-platform-data-dev"
snapshot_builder_image = "us-docker.pkg.dev/YOUR_DEV_PROJECT/handlers/snapshot-builder:dev"
manifest_writer_image  = "us-docker.pkg.dev/YOUR_DEV_PROJECT/handlers/manifest-writer:dev"
index_writer_image     = "us-docker.pkg.dev/YOUR_DEV_PROJECT/handlers/index-writer:dev"
rules_engine_image     = "us-docker.pkg.dev/YOUR_DEV_PROJECT/handlers/rules-engine:dev"
