project_id = "YOUR_PROD_PROJECT"
region     = "us-central1"
location   = "US"
bucket_name = "ecco-studio-platform-data"
snapshot_builder_image = ""
manifest_writer_image  = ""
index_writer_image     = ""
rules_engine_image     = ""
