project_id = "YOUR_STG_PROJECT"
region     = "us-central1"
location   = "US"
bucket_name = "ecco-studio-platform-data-stg"
snapshot_builder_image = "us-docker.pkg.dev/YOUR_STG_PROJECT/handlers/snapshot-builder:stg"
manifest_writer_image  = "us-docker.pkg.dev/YOUR_STG_PROJECT/handlers/manifest-writer:stg"
index_writer_image     = "us-docker.pkg.dev/YOUR_STG_PROJECT/handlers/index-writer:stg"
rules_engine_image     = "us-docker.pkg.dev/YOUR_STG_PROJECT/handlers/rules-engine:stg"
